config-version = 2

start-at-login = true

# Keep only workspaces 1 to 10 active and persistent.
persistent-workspaces = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = 8
outer.bottom = 8
outer.top = 8
outer.right = 8

[mode.main.binding]
# Workspace navigation.
cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
cmd-7 = 'workspace 7'
cmd-8 = 'workspace 8'
cmd-9 = 'workspace 9'
cmd-0 = 'workspace 10'

# Move node to workspace.
cmd-shift-1 = 'move-node-to-workspace 1'
cmd-shift-2 = 'move-node-to-workspace 2'
cmd-shift-3 = 'move-node-to-workspace 3'
cmd-shift-4 = 'move-node-to-workspace 4'
cmd-shift-5 = 'move-node-to-workspace 5'
cmd-shift-6 = 'move-node-to-workspace 6'
cmd-shift-7 = 'move-node-to-workspace 7'
cmd-shift-8 = 'move-node-to-workspace 8'
cmd-shift-9 = 'move-node-to-workspace 9'
cmd-shift-0 = 'move-node-to-workspace 10'

# Focuses nearest window in direction. Seamlessly crosses monitor boundaries 
# but corrects the vertical monitor layout reversal.
cmd-h = 'focus left --boundaries-action fail || focus-monitor left'
cmd-j = 'focus down --boundaries-action fail || focus-monitor up'     # Fallback goes UP
cmd-k = 'focus up --boundaries-action fail || focus-monitor down'     # Fallback goes DOWN
cmd-l = 'focus right --boundaries-action fail || focus-monitor right'

# Moves window in direction. Seamlessly crosses monitor boundaries
# but corrects the vertical monitor layout reversal and ensures focus follows.
cmd-shift-h = 'move left --boundaries-action fail || move-node-to-monitor left --focus-follows-window'
cmd-shift-j = 'move down --boundaries-action fail || move-node-to-monitor up --focus-follows-window'     # Fallback goes UP
cmd-shift-k = 'move up --boundaries-action fail || move-node-to-monitor down --focus-follows-window'     # Fallback goes DOWN
cmd-shift-l = 'move right --boundaries-action fail || move-node-to-monitor right --focus-follows-window'

# Window layouts and splitting.
cmd-b = 'join-with left'
cmd-v = 'join-with up'
cmd-s = 'layout v_accordion'
cmd-w = 'layout h_accordion'
cmd-e = 'layout tiles horizontal vertical'
cmd-f = 'fullscreen'
cmd-shift-space = 'layout floating tiling'

# Sway-like scratchpad emulation.
cmd-minus = 'workspace --auto-back-and-forth SP'
cmd-shift-minus = 'move-node-to-workspace SP'

# Window management.
cmd-shift-q = 'close'
cmd-shift-c = 'reload-config'

# Disable native quitting shortcuts globally to prevent accidental application
# quits.
cmd-q = []

# Quick Terminal Launch.
cmd-enter = 'exec-and-forget open -n -a Ghostty'

# Sway-like resize mode trigger.
cmd-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -10'
j = 'resize height +10'
k = 'resize height -10'
l = 'resize width +10'
enter = 'mode main'
esc = 'mode main'

# Map workspaces to specific displays:
#
# NOTE: You can use aerospace list-monitors to get the specific monitor names.
[workspace-to-monitor-force-assignment]
"1" = 'built-in'
"2" = 'built-in'
"3" = 'built-in'

"4" = ['vx3276-qhd', 2, 'built-in']
"5" = ['vx3276-qhd', 2, 'built-in']
"6" = ['vx3276-qhd', 2, 'built-in']
"7" = ['vx3276-qhd', 2, 'built-in']

"8" = ['24g2w1g5', 3, 'built-in']
"9" = ['24g2w1g5', 3, 'built-in']
"10" = ['24g2w1g5', 3, 'built-in']
